/*
SQLmap Wrapper for Burpsuite.
Copyright (C) 2011-2012  Daniel Garcia (cr0hn) | dani@iniqua.com | twitter: @ggdaniel

Based on code of @NighterMan

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
/*
 * PluginTab.java
 *
 * Created on 16-feb-2012, 23:17:03
 */

package CustomPlugin.wfuzz;

import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Daniel Garcia Garcia (cr0hn) - dani@iniqua.com
 */
public class wfuzzTab extends javax.swing.JPanel implements Runnable {

    Highlighter.HighlightPainter myHighlightPainter = new MyHighlightPainter(Color.YELLOW);
    private JTabbedPane tabpanel;
    private Thread _th;
    private ForkWorker _for;

    // A private subclass of the default highlight painter
    class MyHighlightPainter extends DefaultHighlighter.DefaultHighlightPainter {
        public MyHighlightPainter(Color color) {
            super(color);
        }
    }


    /** Creates new form PluginTab */
    public wfuzzTab(List command, String URL, JTabbedPane tabPane) throws IOException {
        this.tabpanel = tabPane;
        initComponents();

        this.txt_URL.setText(URL);

        // Run process
        ProcessBuilder builder = new ProcessBuilder(command);
        builder.start();
        
        builder.redirectErrorStream(true);
        this._for = new ForkWorker(this.txt_console, builder);
    }

    public void run() {
        this._for.execute();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_console = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_select_file = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_URL = new javax.swing.JTextField();

        txt_console.setBackground(new java.awt.Color(0, 0, 0));
        txt_console.setColumns(20);
        txt_console.setFont(new java.awt.Font("Dialog", 0, 14));
        txt_console.setForeground(new java.awt.Color(102, 204, 0));
        txt_console.setLineWrap(true);
        txt_console.setRows(5);
        txt_console.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_consoleKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_console);

        jLabel1.setText("Search:");

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        btn_select_file.setText("Save to file...");
        btn_select_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select_fileActionPerformed(evt);
            }
        });

        btn_close.setText("Close tab");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jLabel2.setText("URL:");

        txt_URL.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_select_file, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_close))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_URL, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_close)
                    .addComponent(btn_select_file))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_select_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select_fileActionPerformed
        JFileChooser jfc = new JFileChooser();
        int rt = jfc.showSaveDialog(this);
        
        if (rt == JFileChooser.APPROVE_OPTION)
        {
            PrintWriter ou = null;
            try {
                ou = new PrintWriter(new FileWriter(jfc.getSelectedFile().getName()));
                ou.write(txt_console.getText());
                ou.close();
            } catch (IOException ex) {
                Logger.getLogger(wfuzzTab.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                ou.close();
            }

        }
    }//GEN-LAST:event_btn_select_fileActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        //this.setVisible(false);
        this.tabpanel.remove(this);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_consoleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_consoleKeyPressed
        this._for.Update(evt.getKeyChar());
    }//GEN-LAST:event_txt_consoleKeyPressed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        removeHighlights(txt_console);
        if(!txt_search.getText().isEmpty())
            highlight(txt_console, txt_search.getText());
    }//GEN-LAST:event_txt_searchKeyTyped


    /**
     * This method highlights a text found in a jtextpane
     *
     * @param textComp: Text pane what contains text
     * @param pattern: Pattern to find into text pane
     */
    private void highlight(JTextComponent textComp, String pattern) {
        // First remove all old highlights
        removeHighlights(textComp);

        Highlighter hilite = textComp.getHighlighter();
        Document doc = textComp.getDocument();
        String text = null;
        try {
            text = doc.getText(0, doc.getLength());
        } catch (BadLocationException ex) {
            Logger.getLogger(wfuzzTab.class.getName()).log(Level.SEVERE, null, ex);
        }
        int pos = 0;

        // Search for pattern
        while ((pos = text.toLowerCase().indexOf(pattern.toLowerCase(), pos)) >= 0) {
            try {
                // Create highlighter using private painter and apply around pattern
                hilite.addHighlight(pos, pos + pattern.length(), myHighlightPainter);
            } catch (BadLocationException ex) {
                Logger.getLogger(wfuzzTab.class.getName()).log(Level.SEVERE, null, ex);
            }
            pos += pattern.length();
        }
    }

    /**
     * This method remove higtlights from a jtextpane
     *
     * @param textComp: Text pane what contains text
     */
    private void removeHighlights(JTextComponent textComp) {
        Highlighter hilite = textComp.getHighlighter();
        Highlighter.Highlight[] hilites = hilite.getHighlights();

        for (int i=0; i<hilites.length; i++) {
            if (hilites[i].getPainter() instanceof MyHighlightPainter) {
                hilite.removeHighlight(hilites[i]);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_select_file;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_URL;
    private javax.swing.JTextArea txt_console;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

}


/**
 * This class execute a command in new thread and display results into jtextpane
 * 
 * @author Daniel Garcia Garcia (cr0hn) - dani@iniqua.com
 */
class ForkWorker extends SwingWorker<String,String> implements Runnable {

    private JTextArea output; // Where to redirect STDERR & STDOUT to
    private ProcessBuilder builder;
    private OutputStream input;

    public ForkWorker(JTextArea output, ProcessBuilder builder) {
        this.output=output;
        this.builder= builder;
    }

    /**
     * This method is called when there is new info to display in text pane.
     *
     * @param chunks
     */
    @Override
    protected void process(java.util.List<String> chunks) {
        // Done on the event thread
        Iterator<String> it = chunks.iterator();
        while (it.hasNext()) {
          output.append(it.next());
        }
    }

    /**
     * This function is called when we want to send some info to process
     *
     * @param text_: Char to write
     */
    public void Update(char text_)
    {
        if(this.input != null)
            try {
                this.input.write(text_);
                this.input.flush();
        } catch (IOException ex) {
            Logger.getLogger(ForkWorker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method start with execution of process
     * 
     */
    public String doInBackground() {
        Process process = null;
        try {
            process = builder.start();
            InputStream res = process.getInputStream();
            this.input = process.getOutputStream();
            
            byte[] buffer = new byte[100];
            int len;
            while ( (len=res.read(buffer,0,buffer.length))!=-1) {
                publish(new String(buffer,0,len));

                if (isCancelled()) {
                    process.destroy();
                    return "";
                }
            }
            this.input.close();
            this.input = null;
        }
        catch (Exception e) {
            process.destroy();
            try {
                this.input.close();
            } catch (IOException ex) {
            }
            this.input = null;
            System.out.println("Error: " + e);
        }
        return "";  // Don't care
    }

    /**
     * This method is called when process are finish.
     */
    @Override
    protected void done() {
        // Done on the swing event thread
        output.append("\n--- EXECUTION IS COMPLETE ---");
    }
}